import type { AgentDefinition } from '@methode-kuate/core'

export const AGENTS_BUSINESS: AgentDefinition[] = [
  {
    id: 'chef-projet',
    name: 'Project Manager',
    nameFr: 'Chef de Projet',
    domain: 'business',
    phase: 'U',
    templateFile: 'chef-projet.hbs',
    description: 'PMBOK project planning, milestones, risk management',
    descriptionFr: 'Planification PMBOK, jalons, gestion des risques',
  },
  {
    id: 'coach-agile',
    name: 'Agile Coach',
    nameFr: 'Coach Agile',
    domain: 'business',
    phase: 'U',
    templateFile: 'coach-agile.hbs',
    description: 'Scrum, Kanban, SAFe facilitation and coaching',
    descriptionFr: 'Facilitation Scrum, Kanban, SAFe et coaching',
  },
  {
    id: 'business-analyst',
    name: 'Business Analyst',
    nameFr: 'Business Analyst',
    domain: 'business',
    phase: 'K',
    templateFile: 'business-analyst.hbs',
    description: 'Requirements, BDD, user stories, process modeling',
    descriptionFr: 'Exigences, BDD, user stories, modélisation de processus',
  },
  {
    id: 'expert-lean',
    name: 'Lean Expert',
    nameFr: 'Expert Lean',
    domain: 'business',
    phase: 'U',
    templateFile: 'expert-lean.hbs',
    description: 'Waste reduction, value stream mapping, continuous improvement',
    descriptionFr: 'Réduction des gaspillages, VSM, amélioration continue',
  },
  {
    id: 'stratege-okr',
    name: 'OKR Strategist',
    nameFr: 'Stratège OKR',
    domain: 'business',
    phase: 'U',
    templateFile: 'stratege-okr.hbs',
    description: 'OKR definition, alignment, tracking and quarterly reviews',
    descriptionFr: 'Définition OKR, alignement, suivi et revues trimestrielles',
  },
  {
    id: 'expert-finance-tech',
    name: 'Tech Finance Expert',
    nameFr: 'Expert Finance Tech',
    domain: 'business',
    phase: 'K',
    templateFile: 'expert-finance-tech.hbs',
    description: 'Budget, ROI, business case, technology investment analysis',
    descriptionFr: 'Budget, ROI, business case, analyse investissement technologique',
  },
]
