import type { AgentDefinition } from '@methode-kuate/core'

export const AGENTS_CONTENT: AgentDefinition[] = [
  {
    id: 'copywriter-technique',
    name: 'Technical Writer',
    nameFr: 'Copywriter Technique',
    domain: 'content',
    phase: 'E',
    templateFile: 'copywriter-technique.hbs',
    description: 'Technical docs, README, tutorials, API documentation',
    descriptionFr: 'Docs techniques, README, tutoriels, documentation API',
  },
  {
    id: 'expert-seo',
    name: 'SEO Expert',
    nameFr: 'Expert SEO',
    domain: 'content',
    phase: 'E',
    templateFile: 'expert-seo.hbs',
    description: 'Search engine optimization, keyword research, content strategy',
    descriptionFr: 'Optimisation SEO, recherche de mots-clés, stratégie de contenu',
  },
  {
    id: 'social-media-strategist',
    name: 'Social Media Strategist',
    nameFr: 'Stratège Réseaux Sociaux',
    domain: 'content',
    phase: 'T',
    templateFile: 'social-media-strategist.hbs',
    description: 'Content calendars, platform strategy, engagement growth',
    descriptionFr: 'Calendriers éditoriaux, stratégie plateforme, croissance engagement',
  },
  {
    id: 'expert-communication',
    name: 'Communication Expert',
    nameFr: 'Expert Communication',
    domain: 'content',
    phase: 'K',
    templateFile: 'expert-communication.hbs',
    description: 'Press relations, stakeholder communication, crisis comms',
    descriptionFr: 'Relations presse, communication stakeholders, gestion de crise',
  },
  {
    id: 'createur-formation',
    name: 'Training Creator',
    nameFr: 'Créateur Formation',
    domain: 'content',
    phase: 'A',
    templateFile: 'createur-formation.hbs',
    description: 'Curriculum design, learning objectives, training materials',
    descriptionFr: 'Conception curriculum, objectifs pédagogiques, supports de formation',
  },
]
