import type { AgentDefinition } from '@methode-kuate/core'

export const AGENTS_DEV: AgentDefinition[] = [
  {
    id: 'architecte-solution',
    name: 'Solution Architect',
    nameFr: 'Architecte Solution',
    domain: 'dev',
    phase: 'A',
    templateFile: 'architecte-solution.hbs',
    description: 'Designs scalable system architecture (TOGAF-aware)',
    descriptionFr: 'Conçoit une architecture système scalable (TOGAF)',
  },
  {
    id: 'dev-senior',
    name: 'Senior Developer',
    nameFr: 'Développeur Senior',
    domain: 'dev',
    phase: 'T',
    templateFile: 'dev-senior.hbs',
    description: 'Implements features with TDD and clean code',
    descriptionFr: 'Implémente avec TDD et clean code',
  },
  {
    id: 'expert-devops',
    name: 'DevOps Expert',
    nameFr: 'Expert DevOps',
    domain: 'dev',
    phase: 'T',
    templateFile: 'expert-devops.hbs',
    description: 'CI/CD, Docker, Kubernetes automation',
    descriptionFr: 'CI/CD, Docker, Kubernetes, automatisation',
  },
  {
    id: 'expert-securite',
    name: 'Security Expert',
    nameFr: 'Expert Sécurité',
    domain: 'dev',
    phase: 'A',
    templateFile: 'expert-securite.hbs',
    description: 'OWASP, threat modeling, security audit',
    descriptionFr: 'OWASP, threat modeling, audit de sécurité',
  },
  {
    id: 'qa-strategist',
    name: 'QA Strategist',
    nameFr: 'Stratège QA',
    domain: 'dev',
    phase: 'E',
    templateFile: 'qa-strategist.hbs',
    description: 'Risk-based testing and quality strategy',
    descriptionFr: 'Tests basés sur le risque et stratégie qualité',
  },
  {
    id: 'tech-lead',
    name: 'Tech Lead',
    nameFr: 'Tech Lead',
    domain: 'dev',
    phase: 'T',
    templateFile: 'tech-lead.hbs',
    description: 'Code review, technical mentoring, standards',
    descriptionFr: 'Revue de code, mentoring technique, standards',
  },
  {
    id: 'expert-performance',
    name: 'Performance Expert',
    nameFr: 'Expert Performance',
    domain: 'dev',
    phase: 'E',
    templateFile: 'expert-performance.hbs',
    description: 'Profiling, optimization, Core Web Vitals',
    descriptionFr: 'Profiling, optimisation, Core Web Vitals',
  },
  {
    id: 'expert-ia-ml',
    name: 'AI/ML Expert',
    nameFr: 'Expert IA/ML',
    domain: 'dev',
    phase: 'T',
    templateFile: 'expert-ia-ml.hbs',
    description: 'AI model integration and MLOps',
    descriptionFr: 'Intégration de modèles IA et MLOps',
  },
]
